# Generated by Django 4.2.3 on 2023-09-13 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('head', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryvnumber', models.CharField(default='', max_length=20)),
                ('entrydate', models.DateField()),
                ('entrytime', models.TimeField(default='00:00')),
                ('exitdate', models.DateField()),
                ('exittime', models.TimeField(default='00:00')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vv.park')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.CharField(blank=True, max_length=15, null=True)),
                ('addressline1', models.CharField(blank=True, max_length=15, null=True)),
                ('addressline2', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rasperry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryvnumber', models.CharField(default='', max_length=20)),
                ('entrydate', models.DateField()),
                ('entrytime', models.TimeField(default='00:00')),
                ('exitdate', models.DateField()),
                ('exittime', models.TimeField(default='00:00')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vv.park')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('phno', models.CharField(max_length=13)),
                ('indate', models.DateField()),
                ('intime', models.TimeField(default='00:00')),
                ('outdate', models.DateField()),
                ('outtime', models.TimeField(default='00:00')),
                ('slot_id', models.IntegerField(null=True)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vv.park')),
            ],
        ),
    ]
