# Generated by Django 4.2.3 on 2023-09-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv', '0002_userprofile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
