# Generated by Django 4.2.3 on 2023-10-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv', '0005_razorpaypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField()),
                ('processed_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
