# Generated by Django 4.2.3 on 2023-10-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv', '0007_processedimage_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='Booked', max_length=20),
        ),
    ]
