# Generated by Django 4.2.3 on 2023-10-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='cam2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='intime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='outtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
