# Generated by Django 4.2.6 on 2023-10-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vv', '0003_alter_booking_head'),
        ('vv', '0009_processedimage_cam2_processedimage_intime_and_more'),
    ]

    operations = [
    ]
