# Generated by Django 4.2.6 on 2024-01-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv', '0012_remove_subscription_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='latitude',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='longitude',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
