# Generated by Django 4.2.6 on 2024-02-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vv', '0013_park_latitude_park_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(default='', max_length=30)),
                ('photo', models.ImageField(default='', upload_to='pic')),
                ('latitude', models.CharField(max_length=12, null=True)),
                ('longitude', models.CharField(max_length=12, null=True)),
                ('maxslot', models.IntegerField(default='4')),
                ('hidden', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vv.service_station'),
        ),
        migrations.AlterField(
            model_name='rasperry',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vv.service_station'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vv.service_station'),
        ),
        migrations.DeleteModel(
            name='Park',
        ),
    ]
