# Generated by Django 4.2.6 on 2024-02-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv', '0014_service_station_alter_booking_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_station',
            name='price',
            field=models.FloatField(default='10'),
        ),
    ]
