# Generated by Django 4.2.6 on 2024-02-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv', '0015_service_station_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_station',
            name='place',
            field=models.CharField(default='', max_length=30),
        ),
    ]
