# Generated by Django 4.2.6 on 2024-02-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv', '0016_service_station_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_station',
            name='photo',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
